name: Output
run-name: Exemplo WorkFlow para OutPut, executado por ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
 gerando_output:
  runs-on: ubuntu-latest
  outputs:
    output-shell: ${{steps.exemplo_output.outputs.action_random}}
  steps:
    - name: Gerando output com shell
      id: exemplo_output
      run: |
       ACTIONS_RANDOM=$(($RANDOM))
       echo action_random=$ACTIONS_RANDOM >> $GITHUB_OUTPUT

    - name: Exibindo o output da actions exemplo_output
      run: |
       echo "${{ steps.exemplo_output.outputs.action_random }}"
 exibindo_valores:
    needs: [gerando_output]
    runs-on: ubuntu-latest
    steps:
      - name: Exibindo os outputs do job gerando_output
        run: |
        echo "Output Shell: ${{ needs.gerando_output.outputs.output-shell}}"